### ISSUE TITLE
Is this still actively maintained?

### ISSUE THREAD

**Issue by colindean** [softprops/porteurbars#20]
I'm looking to make a template out of a project and looking for an alternative to giter8, the exact reasons for which the README for Porteurbars illustrates. It's not an sbt or Scala or even JVM thing (really, just a Makefile and a YAML file!). I'd like for this template system to be usable for at least a few years.

However, the lack of recent commits has me hesitant. Is Porteurbars in a "done" state and just works? Would you accept PRs if I found bugs or suggested new functionality?

**Comment by softprops** [comment]
It works for now as is but I don't have any new features planned. The lack of features my strategy for keeping this a working tool.  I am open to pull requests if you have ideas. I'm also open to adding new maintainers if you are interested.

**Comment by colindean** [comment]
Thank you for responding! I don't know how much time I'll have but knowing that the author of the tool is present helps me make the case that I can invest time in its ecosystem!
